version: "3"

services:
  traefik:
    command: --api.insecure=true --providers.docker
    ports:
      - "8000:80"
      - "8001:8080"

  recipes:
    build:
      target: base
    command: dart run --enable-vm-service ./bin/recipes.dart
    volumes:
      - ./services/recipes/lib:/usr/app/services/recipes/lib

  recipes_db:
    command: mongod --quiet --logpath /dev/null

  schedules:
    build:
      target: base
    command: dart run --enable-vm-service ./bin/schedules.dart
    volumes:
      - ./services/schedules/lib:/usr/app/services/schedules/lib

  schedules_db:
    command: mongod --quiet --logpath /dev/null

volumes:
  recipes_db_data: {}
  schedules_db_data: {}
