version: "3"

services:
  traefik:
    labels:
      - "traefik.enable=false"
    image: traefik:v2.8
    command: --providers.docker
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  recipes:
    labels:
      - "traefik.http.routers.recipes.rule=PathPrefix(`/api/recipes`)"
    build:
      context: .
      dockerfile: ./services/recipes/Dockerfile
    image: yourilieverdink/whocooks-recipes:${TAG-latest}
    environment:
      - PREFIX=api/recipes
      - DB_HOST=recipes_db
      - QUEUE_HOST=rabbit_mq
      - VERSION=${TAG:-latest}
    ports:
      - "8080"
    depends_on:
      - recipes_db
      - rabbit_mq

  recipes_db:
    labels:
      - "traefik.enable=false"
    image: mongo
    ports:
      - "27017"
    volumes:
      - recipes_db_data:/data/db

  schedules:
    labels:
      - "traefik.http.routers.schedules.rule=PathPrefix(`/api/schedules`)"
    build:
      context: .
      dockerfile: ./services/schedules/Dockerfile
    image: yourilieverdink/whocooks-schedules:${TAG-latest}
    environment:
      - PREFIX=api/schedules
      - DB_HOST=schedules_db
      - QUEUE_HOST=rabbit_mq
      - VERSION=${TAG:-latest}
    ports:
      - "8080"
    depends_on:
      - schedules_db
      - rabbit_mq

  schedules_db:
    labels:
      - "traefik.enable=false"
    image: mongo
    ports:
      - "27017"
    volumes:
      - schedules_db_data:/data/db

  rabbit_mq:
    image: rabbitmq:3
    ports:
      - "5672"

volumes:
  recipes_db_data: {}
  schedules_db_data: {}
