version: "3"

services:
  traefik:
    labels:
      - "traefik.enable=false"
    image: traefik:v2.8
    command: --providers.docker
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  recipes:
    labels:
      - "traefik.http.routers.recipes.rule=PathPrefix(`/api/recipes`)"
    build:
      context: .
      dockerfile: ./services/recipes/Dockerfile
    image: yourilieverdink/whocooks-recipes:${TAG-latest}
    environment:
      - PREFIX=api/recipes
      - MONGODB_URI=mongodb://recipes-db/whocooks
      - VERSION=${TAG:-latest}
    ports:
      - "8080"
    depends_on:
      - recipes-db

  recipes-db:
    labels:
      - "traefik.enable=false"
    image: mongo
    ports:
      - "27017"
    volumes:
      - recipes-db-data:/data/db

  schedules:
    labels:
      - "traefik.http.routers.schedules.rule=PathPrefix(`/api/schedules`)"
    build:
      context: .
      dockerfile: ./services/schedules/Dockerfile
    image: yourilieverdink/whocooks-schedules:${TAG-latest}
    environment:
      - PREFIX=api/schedules
      - MONGODB_URI=mongodb://schedules-db/whocooks
      - VERSION=${TAG:-latest}
    ports:
      - "8080"
    depends_on:
      - schedules-db

  schedules-db:
    labels:
      - "traefik.enable=false"
    image: mongo
    ports:
      - "27017"
    volumes:
      - schedules-db-data:/data/db

volumes:
  recipes-db-data: {}
  schedules-db-data: {}
