// Mocks generated by Mockito 5.2.0 from annotations
// in app/test/src/state/recipes/recipes_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:app/src/generated/generated.dart' as _i2;
import 'package:app/src/generated/nl_iruoy_whocooks_recipes_client.dart' as _i4;
import 'package:app/src/generated/nl_iruoy_whocooks_recipes_json.dart' as _i5;
import 'package:app/src/services/repository/repository.dart' as _i6;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeNlIruoyWhocooksRecipesClient_0 extends _i1.Fake
    implements _i2.NlIruoyWhocooksRecipesClient {}

class _FakeClient_1 extends _i1.Fake implements _i3.Client {}

class _FakeNlIruoyCommonModelsHealthcheckResource_2 extends _i1.Fake
    implements _i4.NlIruoyCommonModelsHealthcheckResource {}

class _FakeNlIruoyWhocooksRecipesModelsRecipeResource_3 extends _i1.Fake
    implements _i2.NlIruoyWhocooksRecipesModelsRecipeResource {}

class _FakeNlIruoyWhocooksRecipesModelsRecipe_4 extends _i1.Fake
    implements _i5.NlIruoyWhocooksRecipesModelsRecipe {}

/// A class which mocks [Repository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepository extends _i1.Mock implements _i6.Repository {
  MockRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NlIruoyWhocooksRecipesClient get client =>
      (super.noSuchMethod(Invocation.getter(#client),
              returnValue: _FakeNlIruoyWhocooksRecipesClient_0())
          as _i2.NlIruoyWhocooksRecipesClient);
}

/// A class which mocks [NlIruoyWhocooksRecipesClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNlIruoyWhocooksRecipesClient extends _i1.Mock
    implements _i2.NlIruoyWhocooksRecipesClient {
  MockNlIruoyWhocooksRecipesClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_1()) as _i3.Client);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i4.NlIruoyCommonModelsHealthcheckResource get healthchecks =>
      (super.noSuchMethod(Invocation.getter(#healthchecks),
              returnValue: _FakeNlIruoyCommonModelsHealthcheckResource_2())
          as _i4.NlIruoyCommonModelsHealthcheckResource);
  @override
  _i2.NlIruoyWhocooksRecipesModelsRecipeResource get recipes =>
      (super.noSuchMethod(Invocation.getter(#recipes),
              returnValue: _FakeNlIruoyWhocooksRecipesModelsRecipeResource_3())
          as _i2.NlIruoyWhocooksRecipesModelsRecipeResource);
}

/// A class which mocks [NlIruoyWhocooksRecipesModelsRecipeResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNlIruoyWhocooksRecipesModelsRecipeResource extends _i1.Mock
    implements _i2.NlIruoyWhocooksRecipesModelsRecipeResource {
  MockNlIruoyWhocooksRecipesModelsRecipeResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_1()) as _i3.Client);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i7.Future<List<_i5.NlIruoyWhocooksRecipesModelsRecipe>> get(
          {num? limit = 100, num? skip = 0}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [], {#limit: limit, #skip: skip}),
              returnValue:
                  Future<List<_i5.NlIruoyWhocooksRecipesModelsRecipe>>.value(
                      <_i5.NlIruoyWhocooksRecipesModelsRecipe>[]))
          as _i7.Future<List<_i5.NlIruoyWhocooksRecipesModelsRecipe>>);
  @override
  _i7.Future<_i5.NlIruoyWhocooksRecipesModelsRecipe> post(
          _i5.NlIruoyWhocooksRecipesModelsRecipeForm? recipeForm) =>
      (super.noSuchMethod(Invocation.method(#post, [recipeForm]),
              returnValue: Future<_i5.NlIruoyWhocooksRecipesModelsRecipe>.value(
                  _FakeNlIruoyWhocooksRecipesModelsRecipe_4()))
          as _i7.Future<_i5.NlIruoyWhocooksRecipesModelsRecipe>);
  @override
  _i7.Future<_i5.NlIruoyWhocooksRecipesModelsRecipe> putById(
          _i5.NlIruoyWhocooksRecipesModelsRecipeForm? recipeForm,
          {String? id}) =>
      (super.noSuchMethod(Invocation.method(#putById, [recipeForm], {#id: id}),
              returnValue: Future<_i5.NlIruoyWhocooksRecipesModelsRecipe>.value(
                  _FakeNlIruoyWhocooksRecipesModelsRecipe_4()))
          as _i7.Future<_i5.NlIruoyWhocooksRecipesModelsRecipe>);
  @override
  _i7.Future<void> deleteById({String? id}) =>
      (super.noSuchMethod(Invocation.method(#deleteById, [], {#id: id}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
}
